import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const defaultTemplates = [
  {
    name: '出门带',
    description: '出门必带物品清单',
    icon: '🚪',
    items: [
      // 重要
      { name: '身份证', category: '重要' },
      { name: '护照', category: '重要' },
      { name: '钥匙', category: '重要' },
      { name: '小白被', category: '重要' },
      { name: '驾照', category: '重要' },
      // 电子
      { name: '充电器', category: '电子' },
      { name: '手机', category: '电子' },
      { name: '耳机', category: '电子' },
      { name: '充电宝', category: '电子' },
      { name: 'iPad', category: '电子' },
      { name: '相机', category: '电子' },
      { name: '相机充电器', category: '电子' },
      { name: '电脑', category: '电子' },
      { name: '硬盘', category: '电子' },
      { name: '插排', category: '电子' },
      { name: '无人机', category: '电子' },
      { name: '摄像头', category: '电子' },
      { name: '牙刷充电器', category: '电子' },
      // 女生
      { name: '护肤品', category: '女生' },
      { name: '化妆品', category: '女生' },
      { name: '卸妆油', category: '女生' },
      { name: '化妆棉', category: '女生' },
      { name: '洗面奶', category: '女生' },
      { name: '洗护发', category: '女生' },
      { name: '面膜', category: '女生' },
      { name: '发油', category: '女生' },
      { name: '卫生巾/护垫', category: '女生' },
      { name: '防晒', category: '女生' },
      { name: '纸巾', category: '女生' },
      { name: '镊子', category: '女生' },
      { name: '指甲刀', category: '女生' },
      { name: '发卡', category: '女生' },
      { name: '洗漱品', category: '女生' },
      { name: '毛巾', category: '女生' },
      { name: '保暖', category: '女生' },
      { name: '姨妈裤', category: '女生' },
      { name: '牙膏', category: '女生' },
      { name: '牙刷', category: '女生' },
      { name: '梳子', category: '女生' },
      { name: '镜子', category: '女生' },
      { name: '香水', category: '女生' },
      { name: '隐形眼镜', category: '女生' },
      { name: '滴眼液', category: '女生' },
      // 服装
      { name: '内衣裤', category: '服装' },
      { name: '上衣', category: '服装' },
      { name: '裤子', category: '服装' },
      { name: '睡衣', category: '服装' },
      { name: '鞋子', category: '服装' },
      { name: '眼镜', category: '服装' },
      { name: '墨镜', category: '服装' },
      { name: '帽子', category: '服装' },
      { name: '泳衣', category: '服装' },
      { name: '袜子', category: '服装' },
      // 其他
      { name: '转换头', category: '其他' },
      { name: '吹风机', category: '其他' },
      { name: '背包', category: '其他' },
      { name: '雨伞', category: '其他' },
      { name: '资料文件', category: '其他' },
      { name: '药品', category: '其他' },
      { name: '保温杯', category: '其他' },
      { name: '创可贴', category: '其他' },
      { name: '零食', category: '其他' },
      { name: '证件照', category: '其他' },
      { name: '笔', category: '其他' },
      { name: '记事本', category: '其他' },
      { name: '保健品', category: '其他' },
      { name: '眼药水', category: '其他' },
      { name: '风油精', category: '其他' },
    ],
  },
  {
    name: '回家带',
    description: '回家必带物品清单',
    icon: '🏠',
    items: [
      { name: '身份证', category: '重要' },
      { name: '钥匙', category: '重要' },
      { name: '充电器', category: '电子' },
      { name: '耳机', category: '电子' },
      { name: '充电宝', category: '电子' },
      { name: '换洗衣服', category: '服装' },
      { name: '袜子内衣', category: '服装' },
      { name: '隐形眼镜', category: '护肤品' },
      { name: '滴眼液', category: '护肤品' },
      { name: '化妆品', category: '护肤品' },
      { name: '卸妆油', category: '护肤品' },
      { name: '面膜', category: '护肤品' },
      { name: '牙刷', category: '其他' },
      { name: '护垫', category: '其他' },
      { name: '保健品', category: '其他' },
      { name: '香水', category: '其他' },
      { name: '小朋友', category: '其他' },
      { name: '眼药水', category: '其他' },
    ],
  },
  {
    name: '短途旅行',
    description: '短途旅行必带物品',
    icon: '🚗',
    items: [
      { name: '身份证', category: '重要' },
      { name: '钥匙', category: '重要' },
      { name: '充电器', category: '电子' },
      { name: '耳机', category: '电子' },
      { name: '充电宝', category: '电子' },
      { name: '手表充电', category: '电子' },
      { name: '内衣裤', category: '服装' },
      { name: '衣服', category: '服装' },
      { name: '睡衣', category: '服装' },
      { name: '墨镜', category: '服装' },
      { name: '护肤', category: '洗护' },
      { name: '牙刷', category: '洗护' },
      { name: '护理卫生巾', category: '洗护' },
      { name: '隐形眼镜', category: '洗护' },
      { name: '滴眼液', category: '洗护' },
      { name: '芦荟胶', category: '洗护' },
      { name: '防晒霜', category: '洗护' },
      { name: '香水', category: '洗护' },
      { name: '眼药水', category: '健康' },
      { name: '药品', category: '健康' },
      { name: '药保健品', category: '健康' },
      { name: '消毒酒精', category: '健康' },
      { name: '驱蚊', category: '健康' },
      { name: '小白', category: '其他' },
      { name: '雨伞', category: '其他' },
      { name: '烧水壶', category: '其他' },
      { name: '耳环', category: '其他' },
      { name: '项链', category: '其他' },
    ],
  },
  {
    name: '娃日常',
    description: '带娃日常出门必备',
    icon: '👶',
    items: [
      { name: '尿不湿', category: '日常' },
      { name: '隔尿垫', category: '日常' },
      { name: '湿巾', category: '日常' },
      { name: '云柔巾', category: '日常' },
      { name: '奶瓶', category: '日常' },
      { name: '奶粉', category: '日常' },
      { name: '热水', category: '日常' },
      { name: '凉水', category: '日常' },
      { name: '纱巾', category: '日常' },
      { name: '毯子', category: '日常' },
      { name: '充电宝', category: '日常' },
      { name: '通风垫', category: '日常' },
      { name: '背带', category: '日常' },
      { name: '换衣服', category: '日常' },
      { name: '婴儿车', category: '日常' },
      { name: '垃圾袋', category: '日常' },
      { name: '面霜', category: '日常' },
      { name: '袜子', category: '日常' },
      { name: '围嘴', category: '日常' },
      { name: '帽子', category: '日常' },
      { name: '辅食碗', category: '辅食' },
      { name: '辅食勺', category: '辅食' },
      { name: '辅食锅', category: '辅食' },
      { name: '辅食油', category: '辅食' },
    ],
  },
  {
    name: '娃旅行',
    description: '带娃旅行完整清单',
    icon: '✈️👶',
    items: [
      { name: '奶瓶', category: '喂养' },
      { name: '奶粉', category: '喂养' },
      { name: '奶瓶刷', category: '喂养' },
      { name: '烧水杯', category: '喂养' },
      { name: '喝水杯', category: '喂养' },
      { name: '液体辅食', category: '喂养' },
      { name: '辅食', category: '喂养' },
      { name: '吃饭围兜', category: '喂养' },
      { name: '零食', category: '喂养' },
      { name: '果泥', category: '喂养' },
      { name: '身份证件', category: '重要' },
      { name: '尿不湿', category: '护理' },
      { name: '隔尿垫', category: '护理' },
      { name: '湿巾', category: '护理' },
      { name: '浴巾', category: '护理' },
      { name: '纱巾', category: '护理' },
      { name: '婴儿毯', category: '护理' },
      { name: '牙刷', category: '护理' },
      { name: '婴儿棉签', category: '护理' },
      { name: '指甲刀', category: '护理' },
      { name: '防晒霜', category: '护理' },
      { name: '药品', category: '护理' },
      { name: '婴儿车', category: '出行' },
      { name: '婴儿背带', category: '出行' },
      { name: '高铁坐垫', category: '出行' },
      { name: '充气床', category: '出行' },
      { name: '衣服', category: '服装' },
      { name: '袜子', category: '服装' },
      { name: '帽子', category: '服装' },
      { name: '手套', category: '服装' },
      { name: '鞋子', category: '服装' },
      { name: '围巾', category: '服装' },
      { name: '防水裤', category: '服装' },
      { name: '游泳圈', category: '玩水' },
      { name: '游泳衣', category: '玩水' },
      { name: '洗澡椅', category: '玩水' },
      { name: '洗澡玩具', category: '玩水' },
      { name: '扫描相机', category: '电子' },
      { name: '充电器', category: '电子' },
      { name: 'iPad', category: '电子' },
      { name: '摄像头', category: '电子' },
      { name: '通风垫', category: '其他' },
      { name: '玩具', category: '其他' },
      { name: '书', category: '其他' },
      { name: '小海马', category: '其他' },
    ],
  },
  {
    name: '露营',
    description: '户外露营装备清单',
    icon: '⛺',
    items: [
      { name: '户外推车', category: '装备' },
      { name: '帐篷', category: '装备' },
      { name: '户外椅', category: '装备' },
      { name: '野餐垫', category: '装备' },
      { name: '保温箱', category: '装备' },
      { name: '充气沙发', category: '装备' },
      { name: '雨伞', category: '装备' },
      { name: '刀叉勺子', category: '餐具' },
      { name: '杯子', category: '餐具' },
      { name: '碗', category: '餐具' },
      { name: '一次性手套', category: '餐具' },
      { name: '饮料水', category: '食物' },
      { name: '零食', category: '食物' },
      { name: '冰袋', category: '食物' },
      { name: '毯子', category: '其他' },
      { name: '垃圾袋', category: '其他' },
      { name: '鞋衣服', category: '其他' },
      { name: '跳绳', category: '娱乐' },
      { name: '桌游', category: '娱乐' },
      { name: '扑克', category: '娱乐' },
    ],
  },
];

async function seed() {
  console.log('Seeding database...');

  // Delete existing default templates
  await prisma.checklistTemplate.deleteMany({
    where: { isDefault: true },
  });
  console.log('Cleared existing default templates.');

  // Create default templates
  for (const template of defaultTemplates) {
    await prisma.checklistTemplate.create({
      data: {
        name: template.name,
        description: template.description,
        icon: template.icon,
        isDefault: true,
        items: {
          create: template.items.map((item, index) => ({
            name: item.name,
            category: item.category,
            orderIndex: index,
          })),
        },
      },
    });
    console.log(`Created template: ${template.name} (${template.items.length} items)`);
  }

  console.log('Seeding complete!');
}

seed()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
